server:
  port: 8050

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://userService
          predicates:
            - Path=/user/**
          filters:
            - name: USERSERVICE
              args:
                name: USESERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENTSERVICE
          uri: lb://departmentService
          predicates:
            - Path=/department/**
          filters:
            - name: USERSERVICE
              args:
                name: USESERVICE
                fallbackuri: forward:/departmentServiceFallBack

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost