server:
  port: 8085

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamjha007/user_dep_microservice_config
          clone-on-start: true