server:
  port: 8070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhot:8060/eureka/
    instance:
      hostname: localhost